# Force the controller to use the internal clock oscillator instead of the crystal
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# Enable experimental connection settings to fix modern Windows handshakes
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y